module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  config: 0
  dblog: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  path: 0
  path_alias: 0
  simplytest_import: 0
  simplytest_launch: 0
  simplytest_ocd: 0
  simplytest_projects: 0
  simplytest_tugboat: 0
  system: 0
  text: 0
  toolbar: 0
  tugboat: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  simplytest: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  simplytest_theme: 0
profile: simplytest
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
